package io.openems.edge.meter.landis.dlms;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;


@ObjectClassDefinition(name = "Meter Landis DLMS", description = "A Landis meter that communicates via DLMS.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter-landis-0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Outstation", description = "Meter outstation used for profile CSV file names.")
	String outstation() default "0001";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "DLMS Bridge-ID", description = "ID of DLMS Bridge.")
	String dlms_id() default "bridgeDlmsSerial0";

	@AttributeDefinition(name = "DLMS Bridge target filter", description = "This is auto-generated by 'DLMS Bridge-ID'.")
	String dlms_target() default "(enabled=true)";

	@AttributeDefinition(name = "Server Address", description = "DLMS Server Address (Physical)")
	int serverAddress() default 9938;

	@AttributeDefinition(name = "Use Logical Name Referencing", description = "Standard is LN (true). Use false for SN referencing meters.")
	boolean useLogicalNameReferencing() default false;

	@AttributeDefinition(name = "Enable auto profile CSV read", description = "Read yesterday's DLMS profile once per day and write it to CSV.")
	boolean autoReadProfile() default true;

	@AttributeDefinition(name = "Profile OBIS", description = "OBIS code of the ProfileGeneric object.")
	String profileObis() default "1.0.99.1.0.255";

	@AttributeDefinition(name = "Auto profile read time", description = "Daily local time in HH:mm format.")
	String autoReadProfileTime() default "00:10";

	@AttributeDefinition(name = "Profile CSV data directory", description = "Directory for daily profile CSV files.")
	String profileCsvDataDir() default "data";

	String webconsole_configurationFactory_nameHint() default "Meter Landis DLMS [{id}]";
}
